package com.espressif.iot.log;

import org.apache.log4j.Level;
import org.apache.log4j.Logger;

// it is generated by python
public class InitLogger {

	public static void init() {
		// ######content######
		ConfigureLog4J.configure();
		Logger.getLogger(com.afunx.softapconnectcompattester.MainActivity.class)
				.setLevel(Level.DEBUG);
		Logger.getLogger(
				com.afunx.softapconnectcompattester.MyApplication.class)
				.setLevel(Level.DEBUG);
		Logger.getLogger(
				com.afunx.xml.model.persistence.SoftApPersistentor.class)
				.setLevel(Level.DEBUG);
		Logger.getLogger(com.afunx.util.FileUtil.class).setLevel(Level.OFF);
	}
}